spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # SQL query formatting

logging:
  file:
    name: basic_java.log
logging.level:
  org.hibernate.SQL:  # SQL query
  org.hibernate.type : trace # SQL query parameters
