name: Code Review with GPT

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install openai requests

    - name: Generate diff for code review
      id: diff
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
        git diff origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }} > pr_diff.txt
      shell: bash

    - name: Perform Code Review with GPT and Comment on Changed Lines
      id: gpt_review
      run: |
        python <<EOF
        import openai
        import requests
        import json

        # OpenAI API Key 설정
        openai.api_key = "${{ secrets.OPENAI_API_KEY }}"

        # 시스템 프롬프트 및 모델명 가져오기
        system_prompt = """${{ secrets.SYSTEM_PROMPT }}"""
        model_name = "${{ secrets.OPENAI_MODEL }}"

        # 처리된 파일과 라인 기록 (중복 방지)
        processed_files = set()  # 각 파일을 기록
        processed_lines = set()  # 각 라인을 기록

        # GitHub API 호출 로그
        print("Fetching changed files from GitHub API...")

        # 변경된 파일과 라인 정보를 가져오기 위한 GitHub API 호출
        files_url = "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        headers = {"Authorization": f"token ${{ secrets.GITHUB_TOKEN }}"}
        try:
            response = requests.get(files_url, headers=headers, timeout=10)
            print(f"GitHub API status code: {response.status_code}")  # 상태 코드 로그 출력
            response.raise_for_status()
        except requests.exceptions.RequestException as e:
            print(f"Error fetching files: {e}")
            exit(1)

        if response.status_code == 200:
            print("Files fetched successfully. Analyzing changes...")
            files_changed = response.json()
            print(f"Files Changed: {files_changed}")  # 응답 데이터 출력

            for file in files_changed:
                file_path = file['filename']
                
                # 이미 처리한 파일은 건너뛰기
                if file_path in processed_files:
                    print(f"Skipping already processed file: {file_path}")
                    continue

                # .java 파일만 처리
                if not file_path.endswith('.java'):
                    print(f"Skipping non-Java file: {file_path}")
                    continue

                print(f"Processing file: {file_path}")
                patch = file.get('patch', '')
                print(f"Analyzing patch for file: {file_path}")

                # 각 라인 중복 처리 방지
                removed_lines = []
                added_lines = []

                for line in patch.split('\n'):
                    if line in processed_lines:
                        print(f"Skipping already processed line: {line}")
                        continue

                    if line.startswith('-') and not line.startswith('***'):  # 삭제된 라인
                        removed_lines.append(line[1:].strip())
                    elif line.startswith('+') and not line.startswith('+++'):  # 추가된 라인
                        added_lines.append(line[1:].strip())

                    # 처리된 라인 기록
                    processed_lines.add(line)

                # 각 파일을 처리한 후 파일 이름을 기록
                processed_files.add(file_path)

                # 삭제된 라인과 추가된 라인을 모두 컨텍스트로 GPT에게 전달
                for added_line in added_lines:
                    context = "\n".join(removed_lines + [added_line])  # 삭제된 라인과 추가된 라인을 컨텍스트로 묶기

                    if added_line:  # 추가된 내용이 있을 때만 GPT 분석
                        print(f"Calling GPT API for added line: {added_line}")
                        try:
                            # OpenAI API 호출에 타임아웃 설정 (30초로 설정)
                            gpt_response = openai.chat.completions.create(
                                model=model_name,
                                messages=[
                                    {"role": "system", "content": system_prompt},
                                    {"role": "user", "content": f"Here is the code diff for context:\n{context}"}
                                ],
                                timeout=30  # 타임아웃 30초로 설정
                            )
                        except Exception as e:
                            print(f"Error in GPT request: {e}")
                            continue

                        review_comment = gpt_response.choices[0].message.content
                        print(f"GPT response received for file: {file_path}")
                        print(f"Review comment: {review_comment}")  # GPT 응답 데이터 출력

                        # 변경된 파일과 라인에 리뷰 코멘트를 추가
                        position = file['changes']  # 변경된 라인 위치 정보
                        comment_body = {
                            "body": review_comment,
                            "path": file_path,
                            "position": position
                        }

                        comment_url = f"https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments"
                        print(f"Posting comment to GitHub for file: {file_path}")
                        requests.post(comment_url, headers=headers, data=json.dumps(comment_body))
                        print(f"Comment posted successfully for file: {file_path}")  # 댓글이 성공적으로 포스팅됐는지 확인
        else:
            print(f"Unexpected status code: {response.status_code}")
            exit(1)

        # 리뷰가 완료된 후 최종 요약 코멘트를 PR에 추가
        final_comment = "### 최종 리뷰 요약: .java 파일에 대한 모든 변경 사항을 검토 완료했습니다."
        comment_url = f"https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
        requests.post(comment_url, headers=headers, data=json.dumps({"body": final_comment}))
        print("Final review comment posted.")

        # 리뷰 완료 후 종료
        print("Review completed. Exiting...")
        exit(0)
        EOF
